name = "deploys-app--dropbox"
main = "src/index.js"
compatibility_date = "2023-09-22"

[vars]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "deploys-dropbox"

[[analytics_engine_datasets]]
binding = "WAE"
dataset = "deploys_dropbox"
