name: Test
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: lts
    - uses: oven-sh/setup-bun@v1
    - run: bun install
    - run: bun run test
